language: groovy
services: mongodb
addons:
  apt:
    sources:
      - mongodb-upstart
      - mongodb-3.2-precise
    packages:
    - mongodb-org-server
    - mongodb-org-shell
sudo: false
before_script:
  - mongo test_calcdb --eval 'db.createCollection("locations");'
  - mongo test_calcdb --eval 'db.createCollection("designs");'
  - mongo test_calcdb --eval 'db.createCollection("structures");'
  - mongo test_calcdb --eval 'db.createCollection("analyses");'
